Repository Clueless-Community/clueless-official-website, pull requests merged in 2022-12, with the labels that each got.

#457 [Update] : Clueless Favicon Icon Change
  public/ClueLess Logo with Bg.png
Labels: codepeak22, 1-POINT

#460 navbar responsive issue fixed
  pages/components/shared/Navbar/ModeSelect.tsx
  pages/components/shared/Navbar/Navbar.tsx
Labels: codepeak22, EASY

#464 multiple oracle from techstack-issues resolved
  database/techstacks.ts
Labels: codepeak 22, points:5

#467 resolved the bug (issue 463)
  pages/components/shared/Navbar/Navbar.tsx
Labels: codepeak 22, points:5
