Repository Clueless-Community/clueless-official-website, pull requests merged in 2023-03, with the labels that each got.

#516 Add: `WorldOfOpenSource`
  pages/components/home/WorldOfOpenSource/WorldOfOpenSource.tsx
  pages/index.tsx
Labels: HARD, JWOC

#519 Fixes #497 [`Footer`]
  package-lock.json
  pages/components/home/WorldOfOpenSource/WorldOfOpenSource.tsx
  pages/components/shared/Footer.tsx
  pages/index.tsx
Labels: EASY, JWOC

#523 Closes #503 [`What is Clueless`]
  pages/components/home/WhatIsClueless/WhatIsClueless.tsx
  pages/index.tsx
Labels: EASY, JWOC

#520 exploreProjects section done
  package-lock.json
  package.json
  pages/components/home/Copilot/py.tsx
  pages/components/home/ExploreProjects/ExploreCard.tsx
  pages/components/home/ExploreProjects/ExploreProjects.tsx
  pages/index.tsx
  public/ClueLess Logo.png
Labels: MEDIUM, JWOC

#513 created lacking skills
  pages/components/home/lackingskills/lackingskills.tsx
  pages/index.tsx
Labels: MEDIUM, JWOC

#512 Added the open source in components of home
  pages/components/home/OpenSource/mainOpenSource.tsx
  pages/components/home/OpenSource/mobileOpenSource.tsx
  pages/components/home/OpenSource/pcOpenSource.tsx
  pages/index.tsx
  public/Gssoc.png
  public/LFX.png
  public/MLH.png
  styles/globals.css
Labels: MEDIUM, JWOC

#527 Closes #493 `new/HeroSection`
  package-lock.json
  package.json
  pages/components/home/HeroSection/HeroSection.tsx
  pages/components/home/HeroSection/NavBar.tsx
  pages/components/home/Tutorial Hell/go.tsx
  pages/components/home/Tutorial Hell/js.tsx
  pages/components/home/Tutorial Hell/py.tsx
  pages/components/home/Tutorial Hell/tutorial_hell.tsx
  pages/components/home/WorldOfOpenSource/WorldOfOpenSource.tsx
  pages/index.tsx
Labels: HARD, JWOC
